language: node_js
before_deploy:
  - npm run dist
deploy:
  provider: npm
  email: technik@kununu.com
  api_key:
    secure: Le1Tgu1xoHXKqXVko2l4/Jp7o3xdRSi8nSYjlMfhyPvRSh1EFoWB4+200cE37Kca40Ix6x4KHDHOiuY67hLHQ5yXAuYk9GzMzdxBuEUiUsw4D8S1RlhK+i573LKlcuzLL9XQ0CHLR87g8yIz11PyrENkVenCELC1zO49KkuZZxBaxGZeTGxQG+r091iDqjzqgAUUVkty6m56H+70uL+brSt0hTVhawRBHa7tCFhXUTIAPqxkhtnunvv2Qd7VSM7X7LcmBt+ZTJ/dmYlDyvqaDdBxrSsK6n+VDKvB5/hQoKPjf6Xo/tMWfeL20HqfRPEFIF6+rOiiVVa+tHcwN6hEteBAvCBUr9ItBSPFP8FOeEQn1lBjOYozXvnMDm6nonddqJWDeq441+jnX3Hi9zVNtUIUzTNXxLlx44ONUhyx2PBTy/DnR8ETf2SULIBDfxSMGlEzyydYK6PbFBZtvHCxrCgY/D3CgO/54ZO5dThsU4J92qP7vU+f6BpwZk1TB/CuY+HnSE82RnJ8jqbeOALKu+qnaYiOc7EDHCAnh5UtX/scpZ16yYepluODJqGCEHgmaRSzGzsEw4x2zIXmAKjiZGWtME4U4KTkUNrbuBOvEd1cuVixFU+vOGuqvYAuoMGfb7y3+a0b9UAvukVz+qqyK+z3Kb7FtIfGVtaQxpQ0vt4=
  on:
    tags: true
    branch: master
    repo: kununu/nukleus
notifications:
  email: false
node_js:
  - "7"
install:
  - npm install --ignore-scripts
script:
  - npm run lint
  - npm run test
  - cd docs
  - npm i
  - npm run lint
